name: test-output
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      num: ${{ steps.assign.outputs.num }}
    steps:
      - id: assign
        run: |
          echo "num=12345" >> "$GITHUB_OUTPUT"
      - name: The job has succeeded
        run: echo 'test the job'
        if: ${{ failure() }}
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Fetch the variable value
        run: |
          echo "value of the var is ${{ needs.build.outputs.num }}"
  fail:
    runs-on: ubuntu-latest
    steps:
      - name: failure
        run: exit 1
      - name: test failure
        run: echo 'kalai'
        if: ${{ failure() }}
        
  
